### PR TITLE
Add custom DriverPath to Start-SeChrome (#59)

### PR DESCRIPTION
**Pull request by adamdriscoll**
* Add DriverPath to Start-SeChrome
to enable loading a specific version of ChromeDriver.

* clean up scoping debug test

### CODE REVIEW

**Comment by adamdriscoll** [comment]
I realized that I merged to develop for and now there are some merge conflicts. This wasn't my intention and I think I'll do away with the develop branch as it overcomplicates the need for that in this project. I can work out these conflicts.

**Comment by craigofnz** [comment]
I suggest backing out of this one and getting the larger change set from #58 in, which in a subsequent commit implemented something similar to this PR. I'll need to check #58 against my own local feature branches.

Suggest smaller, more focussed PR's moving forward.

**Comment by jhoneill** [comment]
@craigofnz  Yes #58 was an unusually big PR , 
In azure devops the test machines use in environment variables, to hold the path to the web drivers for chrome, firefox and (on windows) IE, so from #58 those variables are noted. 
Edge Dev (on build 80 and 81) needs the web driver to be in the same folder as the browser (the binary path is ignored).  I suspect this issue originates with applies to the chrome driver so you may have to do the same thing if the v80/81 and the canary build of Chrome. 

So all 4 of these now have a command line parameter AND pick up the web driver from an environment variable if one is set.   If you set the environment variable it saves specifying it on each start.

**Comment by craigofnz** [comment]
@adamdriscoll  Please cancel this PR, as @jhoneill included the same as parameter `-WebDriverDirectory`.

**Pull request closed without merging**
